version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    commit-message:
      prefix: '[Dependabot]'
    schedule:
      interval: weekly
      time: '03:00'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'riscv-arch-test'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
