name: NEORV32 RISCOF Verification

on:
  push:
  workflow_dispatch:

jobs:

  neorv32-verification:
    runs-on: ubuntu-22.04

    steps:

    - name: '📂 Repository checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: '📦 Install Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: '📦 Install xPack RISC-V GCC 14.2.0'
      run: |
        wget -q https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v14.2.0-2/xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz
        mkdir $GITHUB_WORKSPACE/riscv-gcc
        tar -xzf xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz -C $GITHUB_WORKSPACE/riscv-gcc
        echo $GITHUB_WORKSPACE/riscv-gcc/xpack-riscv-none-elf-gcc-14.2.0-2/bin >> $GITHUB_PATH

    - name: '📦 Install Sail RISC-V model'
      run: |
        mkdir $GITHUB_WORKSPACE/sail-riscv
        tar -xzf $GITHUB_WORKSPACE/bin/sail-riscv.tar.gz -C $GITHUB_WORKSPACE/sail-riscv
        echo $GITHUB_WORKSPACE/sail-riscv >> $GITHUB_PATH

    - name: '📦 Install RISCOF'
      run: |
        echo "upstream RISCOF is broken! https://github.com/riscv-software-src/riscof/issues/122"
        pip3 install git+https://github.com/riscv/riscof.git@d38859f85fe407bcacddd2efcd355ada4683aee4

    - name: '📦 Install GHDL'
      uses: ghdl/setup-ghdl-ci@nightly

    - name: '🔍 Check tools'
      run: |
        python -V
        riscv-none-elf-gcc -v
        riscv_sim_RV32 -h
        riscof --version
        ghdl -v

    - name: '⚙️ Run verification framework'
      run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/run.sh && $GITHUB_WORKSPACE/run.sh"

    - name: '📤 Archive test report'
      uses: actions/upload-artifact@v4
      with:
        name: test_report
        path: |
          riscof_work/report.html
          riscof_work/style.css
